.de TQ
.br
.ns
.TP \\$1
..
.TH XRANDR-UTILS __libmansuffix__ __vendorversion__

.SH NAME
 XrandrUtils \- Wrapper library for libXrandr.
.SH SYNTAX
\&#include <X11/extensions/XrandrUtils.h>
.nf
.sp

.SH DATATYPES

.PP
.B Relations and Geometries
.PP
.nf
typedef enum {
  relation_left_of,
  relation_right_of,
  relation_above,
  relation_below,
  relation_same_as,
} XRURelation;

typedef struct {
  int     x1, y1, x2, y2;
} XRUBox;

typedef struct {
  int     x, y;
} XRUPoint;
.sp
.fi

.SH DESCRIPTION
.B XrandrUtils
is a high level library designed to wrapper the Xrandr library with
a more convenient API for doing common screen configuration operations.

.SH FUNCTIONS
.PP

.SH RESTRICTIONS
.B XrandrUtils
will remain upward compatible after the current 1.0 release.
.SH AUTHOR
Keith Packard, Intel; Bryce Harrington, Canonical.
